<?php

/**
 *
 * Implements hook_menu()
 */
function api_explorer_menu() {
  return array(
    'api-explorer' => array(
      'title' => 'API Explorer',
      'type' => MENU_CALLBACK,
      'page callback' => 'api_explorer_community_data',
      'access callback' => TRUE,
    ),

    'api-explorer/community-data' => array(
      'title' => 'Community Data',
      'type' => MENU_DEFAULT_LOCAL_TASK,
      'access callback' => TRUE,
      'weight' => 0,
    ),

    'api-explorer/agave' => array(
      'title' => 'Agave API',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'api_explorer_agave_api',
      'access callback' => TRUE,
      'weight' => 10,
    ),

    'api-explorer/thalemine' => array(
      'title' => 'Thalemine API',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'api_explorer_thalemine_api',
      'access callback' => TRUE,
      'weight' => 20,
    ),
  );
}

/**
 * Implements hook_theme()
 */
function api_explorer_theme() {
  $template_path = drupal_get_path('module', 'api_explorer'). '/theme';
  return array(
    'api_explorer_community_data_page_header' => array(
      'template' => 'api_header',
      'path' => $template_path,
      'variables' => array(
        'anonymous' => TRUE,
      ),
    ),

    'api_explorer_community_data_service' => array(
      'variables' => array(
        'service' => NULL,
        'name' => '',
        'version' => '',
        'namespace' => '',
        'icon' => '',
        'tags' => '',
        'description' => '',
      ),
      'template' => 'api_app',
      'path' => $template_path
    ),
  );
}

function api_explorer_community_data() {
  global $user;
  $output = array(
    'header' => array(
      '#theme' => 'api_explorer_community_data_page_header',
      '#anonymous' => ($user->uid == 0),
    ),
    'services' => array(
      '#prefix' => '<div id="services" class="row">',
      '#suffix' => '</div>',
    ),
  );
  $all_services = cache_graceful('api_explorer_community_data', array('api_explorer_get_all_services'), 'cache', 150, 30);
  foreach ($all_services as $serviceObj) {
    $key = $serviceObj['name'] . $serviceObj['version'];
    $output['services'][$key] = array(
      '#theme' => 'api_explorer_community_data_service',
      '#service' => $serviceObj,
      '#name' => $serviceObj['name'],
      '#version' => $serviceObj['version'],
      '#namespace' => $serviceObj['namespace'],
      '#icon' => $serviceObj['icon'],
      '#tags' => $serviceObj['tags'],
      '#description' => $serviceObj['description'],
    );
  }

  drupal_add_css(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/css/screen.css');
  drupal_add_css(drupal_get_path('module', 'api_explorer').'/styles/swagger-overrides.css');
  drupal_add_css(drupal_get_path('module', 'api_explorer').'/styles/community-data.css');

  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/moment/min/moment.min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/es6-promise/promise.min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/scripts/promise-polyfill.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/jquery.slideto.min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/jquery.wiggle.min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/jquery.ba-bbq.min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/handlebars-2.0.0.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/underscore-min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/backbone-min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/swagger-ui.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/highlight.7.3.pack.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/marked.js', array('scope' => 'footer'));
  drupal_add_js('window.services = '.json_encode($all_services).';', array('scope' => 'footer', 'type' => 'inline'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/scripts/community-data.js', array('scope' => 'footer'));

  return $output;
}

function api_explorer_agave_api() {
  // TODO
  $markup = <<<HTML
<link href='//fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'/>
<div class="swagger-section">
  <div id="message-bar" class="swagger-ui-wrap">&nbsp;</div>
  <div id="swagger-ui-container" class="swagger-ui-wrap"></div>
</div>
HTML;

  $output = array(
    '#markup' => $markup,
  );

  drupal_add_css(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/css/screen.css');
  drupal_add_css(drupal_get_path('module', 'api_explorer').'/styles/swagger-overrides.css');

  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/es6-promise/promise.min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/scripts/promise-polyfill.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/jquery.slideto.min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/jquery.wiggle.min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/jquery.ba-bbq.min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/handlebars-2.0.0.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/underscore-min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/backbone-min.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/swagger-ui.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/highlight.7.3.pack.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/vendor/swagger-ui-2.1.0/dist/lib/marked.js', array('scope' => 'footer'));
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/scripts/agave-api.js', array('scope' => 'footer'));

  return $output;
}

function api_explorer_thalemine_api() {
  drupal_add_js(drupal_get_path('module', 'api_explorer').'/scripts/thalemine-api.js', array('scope' => 'footer'));
  return array(
    '#markup' => '<div id="thalemine-api"></div>',
  );
}

function api_explorer_get_all_services() {
    $all_services = array();
    $ns_arry = api_explorer_get_namespaces();
    $ns_arry = $ns_arry["result"];
    foreach ($ns_arry as $value) {
      $service_arry = api_explorer_get_services_for_namespace($value["name"]);
      $service_arry = $service_arry["result"];
      if(!empty($service_arry)){
        foreach ($service_arry as $serviceObj) {
          $base64Img = api_explorer_service_get_img($serviceObj);
          $serviceObj['icon'] = $base64Img;
          array_push($all_services, $serviceObj);
        }
      }
    }
    usort($all_services, 'api_explorer_sort_name_version');
    return $all_services;
}


function api_explorer_get_namespaces(){
    $token = variable_get('agave_tenant_token', '');

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api.araport.org/community/v0.3/namespaces');
    curl_setopt($ch, CURLOPT_HTTPHEADER, array("Authorization: Bearer $token"));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $resp = curl_exec($ch);
    $json_obj = json_decode($resp, true);
    usort($json_obj['result'], 'api_explorer_sort_name');
    return $json_obj;
  }

  function api_explorer_sort_name($a, $b){
    return strcmp($a['name'],$b['name']);
  }

  function api_explorer_sort_name_version($a,$b){
    return strcmp($a['name'] . '_v' . $a['version'], $b['name'] . '_v' . $b['version']);
  }

  function api_explorer_get_services_for_namespace($service_name){
    $token = variable_get('agave_tenant_token', '');

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api.araport.org/community/v0.3/' . $service_name . '/services?');
    curl_setopt($ch, CURLOPT_HTTPHEADER, array("Authorization: Bearer $token"));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $resp = curl_exec($ch);
    $json_obj = json_decode($resp, true);
    return $json_obj;
  }

  function api_explorer_service_get_img($srv){
    $token = variable_get('agave_tenant_token', '');

    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $srv['self'] . '/icon');
    curl_setopt($ch, CURLOPT_HTTPHEADER, array("Authorization: Bearer $token"));
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    $resp = curl_exec($ch);

    $http_status_code = curl_getinfo($ch, CURLINFO_HTTP_CODE);
    if($http_status_code == 200){
      $base64 = base64_encode($resp);
    } else {
      $base64 = null;
    }
    return $base64;
  }